ud4.examples.keystore.passwd=123456

ud4.examples.jsse.host=localhost
ud4.examples.jsse.port=1234
ud4.examples.jsse.keystore.passwd=123456

ud4.exercises.cinema.keystore.path=files/ud4/cinema/cinema-server.jks
ud4.exercises.cinema.keystore.password=123456
ud4.exercises.cinema.truststore.path=files/ud4/cinema/cinema-client.jks
ud4.exercises.cinema.truststore.password=123456

ud4.practices.chat.host=localhost
ud4.practices.chat.port=1234
ud4.practices.chat.keystore.path=files/ud4/chat/chat-server.jks
ud4.practices.chat.keystore.passwd=123456
ud4.practices.chat.keystore.alias=chat-server

exam2.keystore.passwd=123456
